using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace DialogueQuests
{
    /// <summary>
    /// Condition that will check random value generated by EffectRandom
    /// </summary>

    [CreateAssetMenu(fileName = "condition", menuName = "DialogueQuests/Conditions/Random", order = 10)]
    public class ConditionRandom : ConditionData
    {
        public override bool IsMet(NarrativeEvent evt, NarrativeCondition condition, Actor player, Actor triggerer) 
        {
            int value = NarrativeManager.Get().GetRandomValue(condition.target_id);
            return condition.CompareInt(value, condition.value_int);
        }

        public override bool ShowTargetID()
        {
            return true;
        }

        public override bool ShowOperatorInt()
        {
            return true;
        }

        public override bool ShowValueInt()
        {
            return true;
        }
    }

}
